### ISSUE TITLE
Need pretrained model

### ISSUE THREAD

**Issue by loaysh2010** [aakaashjois/PyTorch-GOTURN#1]
Can you please share the pre-trained model weights

**Comment by aakaashjois** [comment]
@loaysh2010 Sorry I took so long to respond. I somehow missed the notification.

The pretrained weight are at the root of the repo:
https://github.com/aakaashjois/goturn_pytorch/blob/master/weights.pkl

You can fetch it using [git-lfs](https://git-lfs.github.com/).
